---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  serial: 1
  hosts: all
  remote_user: ansible
  tasks:
    #Install missing updates only if at least one is missing
    – name: Install missing updates.
      win_updates:
        category_names:
          – Application
          – Connectors
          – DefinitionUpdates
          – DeveloperKits
          – FeaturePacks
          – Guidance
          – ServicePacks
          – Tools
          – UpdateRollups
          – CriticalUpdates
          – SecurityUpdates
          - Updates
      register: update_result
    – name: Reboot, if needed.
      win_reboot:
      when: update_result.reboot_required
