---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx and configure auto start
  service:
    name: nginx
    state: started
    enabled: true

- name: Use nginx.conf template 
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx reload

- name: Create nginx group
  group:
    name: "{{ nginx_group }}"
    system: true

- name: Create nginx user
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    groups: "{{ nginx_group }}"
    append: true
    system: true
